const courses = [
  {
    id: 0,
    name: {
      uz: "Bolalar uchun dasturlash",
      ru: "Программирование для детей",
      en: "Programming for kids",
    },
    description: {
      uz: "Bolalar uchun dasturlash kurslarida o'qib malakasi mutaxasisga aylaning!",
      ru: "В курсах по программированию для детей вы получите навыки профессионала!",
      en: "In programming courses for children, you will become a professional!",
    },
    modules: 5,
    duration: 6,
    review: 4.5,
    price: 590000,
    image: "https://picsum.photos/seed/picsum/200/300",
    path: "/courses/web-development",
  },
  {
    id: 0,
    name: {
      uz: "Frontend dasturlash",
      ru: "Frontend разработка",
      en: "Frontend development",
    },
    description: {
      uz: "Frontend dasturlash kurslarida o'qib malakasi mutaxasisga aylaning!",
      ru: "В курсах по фронтенд разработке вы получите навыки профессионала!",
      en: "In frontend development courses, you will become a professional!",
    },
    modules: 5,
    duration: 6,
    review: 4.5,
    price: 590000,
    image: "https://picsum.photos/seed/picsum/200/300",
    path: "/courses/web-development",
  },
  {
    id: 0,
    name: {
      uz: "Backend dasturlash",
      ru: "Backend разработка",
      en: "Backend development",
    },
    description: {
      uz: "Backend dasturlash kurslarida o'qib malakasi mutaxasisga aylaning!",
      ru: "В курсах по backend разработке вы получите навыки профессионала!",
      en: "In backend development courses, you will become a professional!",
    },
    modules: 5,
    duration: 6,
    review: 4.5,
    price: 590000,
    image: "https://picsum.photos/seed/picsum/200/300",
    path: "/courses/web-development",
  },
  {
    id: 0,
    name: {
      uz: "Kiber xavfsizlik",
      ru: "Кибер безопасность",
      en: "Cyber security",
    },
    description: {
      uz: "Kiberxavfsizlik kurslarida o'qib malakasi mutaxasisga aylaning!",
      ru: "В курсах по кибербезопасности вы получите навыки профессионала!",
      en: "In cyber security courses, you will become a professional!",
    },
    modules: 5,
    duration: 6,
    review: 4.5,
    price: 590000,
    image: "https://picsum.photos/seed/picsum/200/300",
    path: "/courses/web-development",
  },
  {
    id: 0,
    name: {
      uz: "Web dizayn",
      ru: "Веб дизайн",
      en: "Web design",
    },
    description: {
      uz: "Web dizayn kurslarida o'qib malakasi mutaxasisga aylaning!",
      ru: "В курсах по веб дизайну вы получите навыки профессионала!",
      en: "In web design courses, you will become a professional!",
    },
    modules: 5,
    duration: 6,
    review: 4.5,
    price: 590000,
    image: "https://picsum.photos/seed/picsum/200/300",
    path: "/courses/web-development",
  },
  {
    id: 0,
    name: {
      uz: "Robototexnika",
      ru: "Робототехника",
      en: "Robotics",
    },
    description: {
      uz: "Robototexnika kurslarida o'qib malakasi mutaxasisga aylaning!",
      ru: "В курсах по робототехнике вы получите навыки профессионала!",
      en: "In robotics courses, you will become a professional!",
    },
    modules: 5,
    duration: 6,
    review: 4.5,
    price: 590000,
    image: "https://picsum.photos/seed/picsum/200/300",
    path: "/courses/web-development",
  },
  {
    id: 0,
    name: {
      uz: "Foundation",
      ru: "Foundation",
      en: "Foundation",
    },
    description: {
      uz: "Foundation kurslarida o'qib malakasi mutaxasisga aylaning!",
      ru: "В курсах по Foundation вы получите навыки профессионала!",
      en: "In Foundation courses, you will become a professional!",
    },
    modules: 5,
    duration: 6,
    review: 4.5,
    price: 590000,
    image: "https://picsum.photos/seed/picsum/200/300",
    path: "/courses/web-development",
  },
];

export default courses;
