const courses = [
  {
    id: 0,
    name: {
      uz: "Frontend dasturlash",
      ru: "Frontend разработка",
      en: "Frontend development",
    },
    description: {
      uz: "Frontend dasturlash kurslarida o'qib malakasi mutaxasiska aylaning!",
      ru: "В курсах по фронтенд разработке вы получите навыки профессионала!",
      en: "In frontend development courses, you will become a professional!",
    },
    modules: 5,
    duration: 6,
    review: 4.5,
    price: 590000,
    image: "https://picsum.photos/seed/picsum/200/300",
    path: "/courses/web-development",
  },
  {
    id: 0,
    name: {
      uz: "Frontend dasturlash",
      ru: "Frontend разработка",
      en: "Frontend development",
    },
    description: {
      uz: "Frontend dasturlash kurslarida o'qib malakasi mutaxasiska aylaning!",
      ru: "В курсах по фронтенд разработке вы получите навыки профессионала!",
      en: "In frontend development courses, you will become a professional!",
    },
    modules: 5,
    duration: 6,
    review: 4.5,
    price: 590000,
    image: "https://picsum.photos/seed/picsum/200/300",
    path: "/courses/web-development",
  },
  {
    id: 0,
    name: {
      uz: "Frontend dasturlash",
      ru: "Frontend разработка",
      en: "Frontend development",
    },
    description: {
      uz: "Frontend dasturlash kurslarida o'qib malakasi mutaxasiska aylaning!",
      ru: "В курсах по фронтенд разработке вы получите навыки профессионала!",
      en: "In frontend development courses, you will become a professional!",
    },
    modules: 5,
    duration: 6,
    review: 4.5,
    price: 590000,
    image: "https://picsum.photos/seed/picsum/200/300",
    path: "/courses/web-development",
  },
  {
    id: 0,
    name: {
      uz: "Frontend dasturlash",
      ru: "Frontend разработка",
      en: "Frontend development",
    },
    description: {
      uz: "Frontend dasturlash kurslarida o'qib malakasi mutaxasiska aylaning!",
      ru: "В курсах по фронтенд разработке вы получите навыки профессионала!",
      en: "In frontend development courses, you will become a professional!",
    },
    modules: 5,
    duration: 6,
    review: 4.5,
    price: 590000,
    image: "https://picsum.photos/seed/picsum/200/300",
    path: "/courses/web-development",
  },
  {
    id: 0,
    name: {
      uz: "Frontend dasturlash",
      ru: "Frontend разработка",
      en: "Frontend development",
    },
    description: {
      uz: "Frontend dasturlash kurslarida o'qib malakasi mutaxasiska aylaning!",
      ru: "В курсах по фронтенд разработке вы получите навыки профессионала!",
      en: "In frontend development courses, you will become a professional!",
    },
    modules: 5,
    duration: 6,
    review: 4.5,
    price: 590000,
    image: "https://picsum.photos/seed/picsum/200/300",
    path: "/courses/web-development",
  },
  {
    id: 0,
    name: {
      uz: "Frontend dasturlash",
      ru: "Frontend разработка",
      en: "Frontend development",
    },
    description: {
      uz: "Frontend dasturlash kurslarida o'qib malakasi mutaxasiska aylaning!",
      ru: "В курсах по фронтенд разработке вы получите навыки профессионала!",
      en: "In frontend development courses, you will become a professional!",
    },
    modules: 5,
    duration: 6,
    review: 4.5,
    price: 590000,
    image: "https://picsum.photos/seed/picsum/200/300",
    path: "/courses/web-development",
  },
];

export default courses;
